#!/bin/sh
jsfiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.jsx\?$' | tr '\n' ' ')
[ -z "$jsfiles" ] && exit 0

diffs=$(node_modules/.bin/prettier --single-quote --print-width 120 --tab-width 4 -l $jsfiles)
[ -z "$diffs" ] && exit 0

echo >&2 "\033[1;33mRun prettier before committing:\033[0m\nnpm run prettier\n"
exit 1
